### ISSUE TITLE
Notification window needs a close button so you don't have to click outside of it to close it

### ISSUE THREAD

**Issue by CliffWade** [joshuapack/MastoPlus#5]
When you click the notification bell in the top right corner and the notification window opens, where the bell was is now a refresh button for the actual notification window. It would be nice if this was changed to an X to close the notification window and the refresh button was moved elsewhere or keep the refresh button where it is and add a close button so that you're not required to click outside of the notification window to close it.

**Comment by joshuapack** [comment]
On mobile it seems to work fine. It maybe a desktop version specific issue.

**Comment by joshuapack** [comment]
Latest release should fix this now. Refresh page and check and see.
